{% set name = "chopin2" %}
{% set version = "1.0.9.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c9216facfb89c8c999b158a499170483dadc25f5638ce4b3724299b4e48258f

build:
  number: 1
  noarch: python
  entry_points:
    - chopin2=chopin2.chopin2:chopin2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.16.3
    - pyspark >=2.40
    - numba >=0.51.2

test:
  imports:
    - chopin2
  commands:
    - pip check
    - chopin2 --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cumbof/chopin2
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: chopin2
  description: |
    Supervised Classification with Hyperdimensional Computing for massive datasets with commodity hardware.
    Supporting k-fold cross-validation and feature selection as backward variable elimination.

extra:
  recipe-maintainers:
    - cumbof
